name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
    
      - name: Set up golangci
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest

      - name: Format
        run: make format

      - name: Lint
        run: make lint
